import Vue from 'vue';
import Vuex from 'vuex';
import Kanmusu from '@/store/kanmusu';

Vue.use(Vuex);

export default new Vuex.Store({
  state: {
    count: 0,
    status: {
      unExists: 0,
      unRemodeled: 1,
      done: 2,
    },
    kanmusu: [
      {
        id : '185',
        name : '龍鳳',
        phonetic : 'りゅうほう',
        shiptype : 'CVL',
        level : 25,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '188',
        name : '利根改二',
        phonetic : 'とねかいに',
        shiptype : 'CAV',
        level : 70,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '189',
        name : '筑摩改二',
        phonetic : 'ちくまかいに',
        shiptype : 'CAV',
        level : 70,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '206',
        name : '雲龍',
        phonetic : 'うんりゅう',
        shiptype : 'CV',
        level : 50,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '211',
        name : '扶桑改二',
        phonetic : 'ふそうかいに',
        shiptype : 'BBV',
        level : 80,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '227',
        name : '鳥海改二',
        phonetic : 'ちょうかいかいに',
        shiptype : 'CA',
        level : 65,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '261',
        name : '翔鶴改二',
        phonetic : 'しょうかくかいに',
        shiptype : 'CV',
        level : 80,
        sekkeizu : 1,
        catapult : 1,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '287',
        name : '鬼怒改二',
        phonetic : 'きぬかいに',
        shiptype : 'CL',
        level : 75,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '288',
        name : '由良改二',
        phonetic : 'ゆらかいに',
        shiptype : 'CL',
        level : 77,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '290',
        name : '荒潮改二',
        phonetic : 'あらしおかいに',
        shiptype : 'DD',
        level : 67,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '303',
        name : '鈴谷改二',
        phonetic : 'すずやかいに',
        shiptype : 'CAV',
        level : 84,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '308',
        name : '鈴谷航改二',
        phonetic : 'すずやこうかいに',
        shiptype : 'CVL',
        level : 88,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '336',
        name : '神鷹改二',
        phonetic : 'しんようかいに',
        shiptype : 'CVL',
        level : 85,
        sekkeizu : 1,
        catapult : 1,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 40,
        status : 0,
      },
      {
        id : '341',
        name : '長門改二',
        phonetic : 'ながとかいに',
        shiptype : 'BB',
        level : 88,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '342',
        name : '夕雲改二',
        phonetic : 'ゆうぐもかいに',
        shiptype : 'DD',
        level : 75,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 1,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '346',
        name : '武蔵改二',
        phonetic : 'むさしかいに',
        shiptype : 'BB',
        level : 89,
        sekkeizu : 3,
        catapult : 0,
        sentoushouhou : 1,
        koukushizai : 0,
        houkoushizai : 3,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '353',
        name : '伊勢改二',
        phonetic : 'いせかいに',
        shiptype : 'BBV',
        level : 88,
        sekkeizu : 2,
        catapult : 1,
        sentoushouhou : 1,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 80,
        status : 0,
      },
      {
        id : '354',
        name : '日向改二',
        phonetic : 'ひゅうがかいに',
        shiptype : 'BBV',
        level : 90,
        sekkeizu : 2,
        catapult : 1,
        sentoushouhou : 1,
        koukushizai : 1,
        houkoushizai : 0,
        kaihatsushizai : 181,
        status : 0,
      },
      {
        id : '366',
        name : '陽炎改二',
        phonetic : 'かげろうかいに',
        shiptype : 'DD',
        level : 70,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 20,
        status : 0,
      },
      {
        id : '391',
        name : '金剛改二丙',
        phonetic : 'こんごうかいにへい',
        shiptype : 'BB',
        level : 92,
        sekkeizu : 2,
        catapult : 0,
        sentoushouhou : 1,
        koukushizai : 0,
        houkoushizai : 2,
        kaihatsushizai : 300,
        status : 0,
      },
      {
        id : '404',
        name : '赤城改二',
        phonetic : 'あかぎかいに',
        shiptype : 'CV',
        level : 90,
        sekkeizu : 2,
        catapult : 1,
        sentoushouhou : 1,
        koukushizai : 2,
        houkoushizai : 0,
        kaihatsushizai : 100,
        status : 0,
      },
    ],
  },
  getters: {
    getKanmusuById: (state) => (id: string) => {
      return state.kanmusu.filter((e) => e.id === id);
    },
    getKanmusuByStatus: (state) => (status: number) => {
      return state.kanmusu.filter((e) => e.status === status);
    },
  },
  mutations: {
    changeStatus: (state, target) => {
      const status: number = parseInt(target.status, 0);
      state.kanmusu.filter((e) => e.id === target.id)[0].status = status;
    },
  },
  actions: {},
});
