import Vue from 'vue';
import Vuex from 'vuex';
import Kanmusu from '@/store/kanmusu';

Vue.use(Vuex);

export default new Vuex.Store({
  state: {
    count: 0,
    status: {
      unExists: 0,
      unRemodeled: 1,
      done: 2,
    },
    kanmusu: [
      {
        id : '185',
        name : '龍鳳',
        phonetic : 'りゅうほう',
        shiptype : 'CVL',
        level : 25,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '188',
        name : '利根改二',
        phonetic : 'とねかいに',
        shiptype : 'CAV',
        level : 70,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '189',
        name : '筑摩改二',
        phonetic : 'ちくまかいに',
        shiptype : 'CAV',
        level : 70,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '206',
        name : '雲龍',
        phonetic : 'うんりゅう',
        shiptype : 'CV',
        level : 50,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '211',
        name : '扶桑改二',
        phonetic : 'ふそうかいに',
        shiptype : 'BBV',
        level : 80,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '227',
        name : '鳥海改二',
        phonetic : 'ちょうかいかいに',
        shiptype : 'CA',
        level : 65,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '261',
        name : '翔鶴改二',
        phonetic : 'しょうかくかいに',
        shiptype : 'CV',
        level : 80,
        sekkeizu : 1,
        catapult : 1,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '287',
        name : '鬼怒改二',
        phonetic : 'きぬかいに',
        shiptype : 'CL',
        level : 75,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '288',
        name : '由良改二',
        phonetic : 'ゆらかいに',
        shiptype : 'CL',
        level : 77,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '290',
        name : '荒潮改二',
        phonetic : 'あらしおかいに',
        shiptype : 'DD',
        level : 67,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '303',
        name : '鈴谷改二',
        phonetic : 'すずやかいに',
        shiptype : 'CAV',
        level : 84,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '308',
        name : '鈴谷航改二',
        phonetic : 'すずやこうかいに',
        shiptype : 'CVL',
        level : 88,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '336',
        name : '神鷹改二',
        phonetic : 'しんようかいに',
        shiptype : 'CVL',
        level : 85,
        sekkeizu : 1,
        catapult : 1,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 40,
        status : 0,
      },
      {
        id : '341',
        name : '長門改二',
        phonetic : 'ながとかいに',
        shiptype : 'BB',
        level : 88,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '342',
        name : '夕雲改二',
        phonetic : 'ゆうぐもかいに',
        shiptype : 'DD',
        level : 75,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 1,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '346',
        name : '武蔵改二',
        phonetic : 'むさしかいに',
        shiptype : 'BB',
        level : 89,
        sekkeizu : 3,
        catapult : 0,
        sentoushouhou : 1,
        koukushizai : 0,
        houkoushizai : 3,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '353',
        name : '伊勢改二',
        phonetic : 'いせかいに',
        shiptype : 'BBV',
        level : 88,
        sekkeizu : 2,
        catapult : 1,
        sentoushouhou : 1,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 80,
        status : 0,
      },
      {
        id : '354',
        name : '日向改二',
        phonetic : 'ひゅうがかいに',
        shiptype : 'BBV',
        level : 90,
        sekkeizu : 2,
        catapult : 1,
        sentoushouhou : 1,
        koukushizai : 1,
        houkoushizai : 0,
        kaihatsushizai : 181,
        status : 0,
      },
      {
        id : '366',
        name : '陽炎改二',
        phonetic : 'かげろうかいに',
        shiptype : 'DD',
        level : 70,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 20,
        status : 0,
      },
      {
        id : '391',
        name : '金剛改二丙',
        phonetic : 'こんごうかいにへい',
        shiptype : 'BB',
        level : 92,
        sekkeizu : 2,
        catapult : 0,
        sentoushouhou : 1,
        koukushizai : 0,
        houkoushizai : 2,
        kaihatsushizai : 300,
        status : 0,
      },
      {
        id : '404',
        name : '赤城改二',
        phonetic : 'あかぎかいに',
        shiptype : 'CV',
        level : 90,
        sekkeizu : 2,
        catapult : 1,
        sentoushouhou : 1,
        koukushizai : 2,
        houkoushizai : 0,
        kaihatsushizai : 100,
        status : 0,
      },
      {
        id : '373',
        name : '陸奥改二',
        phonetic : 'むつかいに',
        shiptype : 'BB',
        level : 89,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '197',
        name : '蒼龍改二',
        phonetic : 'そうりゅうかいに',
        shiptype : 'CV',
        level : 78,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '196',
        name : '飛龍改二',
        phonetic : 'ひりゅうかいに',
        shiptype : 'CV',
        level : 77,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '226',
        name : '吹雪改二',
        phonetic : 'ふぶきかいに',
        shiptype : 'DD',
        level : 70,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '220',
        name : '叢雲改二',
        phonetic : 'むらくもかいに',
        shiptype : 'DD',
        level : 70,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '195',
        name : '綾波改二',
        phonetic : 'あやなみかいに',
        shiptype : 'DD',
        level : 70,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '149',
        name : '金剛改二',
        phonetic : 'こんごうかいに',
        shiptype : 'BB',
        level : 75,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '150',
        name : '比叡改二',
        phonetic : 'ひえいかいに',
        shiptype : 'BB',
        level : 75,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '151',
        name : '榛名改二',
        phonetic : 'はるなかいに',
        shiptype : 'BB',
        level : 80,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '152',
        name : '霧島改二',
        phonetic : 'きりしまかいに',
        shiptype : 'BB',
        level : 75,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '212',
        name : '山城改二',
        phonetic : 'やましろかいに',
        shiptype : 'BBV',
        level : 80,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '277',
        name : '天龍改二',
        phonetic : 'てんりゅうかいに',
        shiptype : 'CL',
        level : 84,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 24,
        status : 0,
      },
      {
        id : '278',
        name : '龍田改二',
        phonetic : 'たつたかいに',
        shiptype : 'CL',
        level : 80,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 15,
        status : 0,
      },
      {
        id : '234',
        name : '睦月改二',
        phonetic : 'むつきかいに',
        shiptype : 'DD',
        level : 65,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '235',
        name : '如月改二',
        phonetic : 'きさらぎかいに',
        shiptype : 'DD',
        level : 65,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '157',
        name : '龍驤改二',
        phonetic : 'りゅうじょうかいに',
        shiptype : 'CVL',
        level : 75,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '218',
        name : '皐月改二',
        phonetic : 'さつきかいに',
        shiptype : 'DD',
        level : 75,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '348',
        name : '文月改二',
        phonetic : 'ふみづきかいに',
        shiptype : 'DD',
        level : 77,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '347',
        name : '多摩改二',
        phonetic : 'たまかいに',
        shiptype : 'CL',
        level : 70,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '146',
        name : '木曾改二',
        phonetic : 'きそかいに',
        shiptype : 'CLT',
        level : 65,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '141',
        name : '五十鈴改二',
        phonetic : 'いすずかいに',
        shiptype : 'CL',
        level : 50,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '158',
        name : '川内改二',
        phonetic : 'せんだいかいに',
        shiptype : 'CL',
        level : 60,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '159',
        name : '神通改二',
        phonetic : 'じんつうかいに',
        shiptype : 'CL',
        level : 60,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '160',
        name : '那珂改二',
        phonetic : 'なかかいに',
        shiptype : 'CL',
        level : 48,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '216',
        name : '古鷹改二',
        phonetic : 'ふるたかかいに',
        shiptype : 'CA',
        level : 65,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '216',
        name : '古鷹改二',
        phonetic : 'ふるたかかいに',
        shiptype : 'CA',
        level : 65,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '191',
        name : '妙高改二',
        phonetic : 'みょうこうかいに',
        shiptype : 'CA',
        level : 70,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '192',
        name : '那智改二',
        phonetic : 'なちかいに',
        shiptype : 'CA',
        level : 65,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '193',
        name : '足柄改二',
        phonetic : 'あしがらかいに',
        shiptype : 'CA',
        level : 65,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '194',
        name : '羽黒改二',
        phonetic : 'はぐろかいに',
        shiptype : 'CA',
        level : 65,
        sekkeizu : 0,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '173',
        name : 'Bismarck zwei',
        phonetic : 'びすまるくつゔぁい',
        shiptype : 'BB',
        level : 50,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '178',
        name : 'Bismarck drai',
        phonetic : 'びすまるくどらい',
        shiptype : 'BB',
        level : 75,
        sekkeizu : 1,
        catapult : 0,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
      {
        id : '345',
        name : 'Saratoga Mk.Ⅱ',
        phonetic : 'さらとがまーくつー',
        shiptype : 'CV',
        level : 85,
        sekkeizu : 1,
        catapult : 1,
        sentoushouhou : 0,
        koukushizai : 0,
        houkoushizai : 0,
        kaihatsushizai : 0,
        status : 0,
      },
    ],
  },
  getters: {
    getKanmusuById: (state) => (id: string) => {
      return state.kanmusu.filter((e) => e.id === id);
    },
    getKanmusuByStatus: (state) => (status: number) => {
      return state.kanmusu.filter((e) => e.status === status);
    },
  },
  mutations: {
    changeStatus: (state, target) => {
      const status: number = parseInt(target.status, 0);
      state.kanmusu.filter((e) => e.id === target.id)[0].status = status;
    },
  },
  actions: {},
});
